SELECT 1;

( SELECT 2 ) UNION   SELECT 3;

SELECT 1 FROM ( SELECT 1 ) al;
SELECT 1 FROM t1;

SELECT 1 FROM (( SELECT 1 )) al;
SELECT 1 FROM ( ( SELECT 2   UNION   SELECT 3 ) ) a;
SELECT 1 FROM (   SELECT 2   UNION   SELECT 3   ) a;
SELECT 1 FROM (   SELECT 2   UNION ( SELECT 3 ) ) a;
SELECT 1 FROM ( ( SELECT 2 ) UNION   SELECT 3   ) a;
SELECT 1 FROM ( ( SELECT 2 ) UNION ( SELECT 3 ) ) a;

SELECT 1 FROM ( SELECT 1 );
SELECT 1 FROM (( SELECT 1 ));

SELECT 1 FROM (   SELECT 2   UNION   SELECT 3   );
SELECT 1 FROM (   SELECT 2   UNION ( SELECT 3 ) );
SELECT 1 FROM ( ( SELECT 2 ) UNION   SELECT 3   );
SELECT 1 FROM ( ( SELECT 2 ) UNION ( SELECT 3 ) );

SELECT 1 FROM t1 JOIN t2;
SELECT 1 FROM t1 JOIN t2 JOIN t3;
SELECT 1 FROM ( t1 JOIN t2 ) JOIN t3;
SELECT 1 FROM t1 JOIN ( t2 JOIN t3 );

SELECT 1 FROM t1;
SELECT 1 FROM (t1);
SELECT 1 FROM ((t1));

SELECT 1 FROM t1 a;
SELECT 1 FROM (t1 a);
SELECT 1 FROM ((t1 a));

SELECT 1 FROM  t1,   t2;
SELECT 1 FROM  t1,   t2;
SELECT 1 FROM (t1),  t2;
SELECT 1 FROM  t1,  (t2);
SELECT 1 FROM (t1), (t2);

SELECT 1 FROM ((t1), t2 );
SELECT 1 FROM ( t1 ,(t2));
SELECT 1 FROM ((t1),(t2));

(SELECT 1);
((SELECT 1));

SELECT 1 FROM ((t1, t2) JOIN t3);
SELECT 1 FROM (((t1, t2)) JOIN t3);
SELECT 1 FROM ((t1, t2) JOIN t3), t4;

SELECT 1;
SELECT (1);
SELECT ((1));

SELECT ((SELECT 1));
SELECT (SELECT 1) = 1;
SELECT ((SELECT 1) = 1);
SELECT ((((SELECT 1)) = 1));

SELECT ((((SELECT 1 UNION SELECT 2)) = 1));

SELECT 1 INTO v;
(SELECT 1 INTO v);
((SELECT 1 INTO v));

SELECT 1 INTO v FROM t1;
(SELECT 1 INTO v FROM t1);
((SELECT 1 INTO v FROM t1));

SELECT 1 FROM t1 INTO v;
(SELECT 1 FROM t1 INTO v);
((SELECT 1 FROM t1 INTO v));

SELECT 1 UNION SELECT 1 INTO v;
(SELECT 1 UNION SELECT 1 INTO v);
((SELECT 1 UNION SELECT 1 INTO v));

SELECT 1 UNION SELECT 1 FROM t1 INTO v;
(SELECT 1 UNION SELECT 1 FROM t1 INTO v);
((SELECT 1 UNION SELECT 1 FROM t1 INTO v));

SELECT 1 UNION SELECT 1 INTO v FROM t1;
(SELECT 1 UNION SELECT 1 INTO v FROM t1);
((SELECT 1 UNION SELECT 1 INTO v FROM t1));

SELECT 1 ORDER BY a;
SELECT 1 INTO v ORDER BY a;
SELECT 1 UNION SELECT 1 ORDER BY a INTO v;

SELECT 1 INTO v FROM t ORDER BY a;
SELECT 1 UNION SELECT 1 INTO v FROM t ORDER BY a;

SELECT 1 INTO v;
SELECT 1 FROM t INTO v;
SELECT 1 FROM t ORDER BY a INTO v;
SELECT 1 FROM t ORDER BY a LIMIT 2 INTO v;

SELECT 1 FROM t1 JOIN t2 JOIN t3 ON 1 ON 2;
SELECT 1 FROM t1 JOIN t2 JOIN t3;
SELECT 1 FROM t1 JOIN t2 ON 1 JOIN t3 ON 2;

  WITH cte AS ( SELECT 1 ) SELECT 2;
 (WITH cte AS ( SELECT 1 ) SELECT 2);
((WITH cte AS ( SELECT 1 ) SELECT 2));

  WITH cte AS ( SELECT 1 ) ( SELECT 2 );

WITH cte AS ( SELECT 1 )    SELECT 2    UNION SELECT 3;
WITH cte AS ( SELECT 1 )  ( SELECT 2 )  UNION SELECT 3;
WITH cte AS ( SELECT 1 ) (( SELECT 2 )) UNION SELECT 3;
SELECT ( WITH cte AS ( SELECT 1 ) SELECT 1 );

SELECT '';
SELECT 'abc';
SELECT '123';
SELECT '!@#$%^&*()';

SELECT *;
SELECT * FROM table1;

DROP TABLE t1;
